[[languages.cpp.environments]]
CXX = "g++"

[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++11", "-Wall", "-O2", "-fsplit-stack"]

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = ["-std=c++17", "-O2", "-Wall"]
